### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by singuerinc** [singuerinc/dial#16]
It's not a chrome extension anymore, but a regular webpage that can be added as homepage in chrome or any browser.

**Comment by agarwalrounak** [comment]
Opening the webpage(https://home.singuerinc.com/) in firefox gives the following screen:

![screenshot from 2018-10-15 01-07-11](https://user-images.githubusercontent.com/38394281/46921294-4b3e4f00-d017-11e8-82f2-4c9b3b4743a7.png)
The links supposed to be under MAIN, NEWS + BLOGS, WEB DEV, etc. are missing. 

Also, there is no option to change the theme from Dark to Light in both chrome and firefox.

**Comment by singuerinc** [comment]
Nice catch, never tested in Firefox...
Seems like in Firefox automatically start in "search mode" so you don't see the links.
I will take a look at that, thanks!

**Comment by agarwalrounak** [comment]
Also, have the option to change the theme from Dark to Light been removed? I can't seem to find them in chrome. If I am correct then it's supposed to be in the bottom right corner.
