### ISSUE TITLE
It starts in "search mode" in Firefox

### ISSUE THREAD

**Issue by singuerinc** [singuerinc/dial#26]
For some reason in Firefox, it starts with focus in the search input. So it is not possible to click on the default links.

I remember that there was an attempt to focus the search while I was developing but it didn't work in Chrome. So such functionality should not be there. My guess is that Firefox automatically focus the page.

### Actual

![screenshot 2018-10-15 at 10 40 13](https://user-images.githubusercontent.com/503676/46939586-f1fe0c00-d066-11e8-9e54-f512267292f6.png)

### Expected

![screenshot 2018-10-15 at 10 44 07](https://user-images.githubusercontent.com/503676/46939708-4ef9c200-d067-11e8-90c3-0abf8e396b41.png)

**Comment by eikybreaky** [comment]
added a [pull request](https://github.com/singuerinc/dial/pull/27) for this issue.
