### ISSUE TITLE
make css responsive

### ISSUE THREAD

**Issue by singuerinc** [singuerinc/dial#5]
The media queries used are not optimal. In mobile, for example, it should be a single column.

**Comment by mameaw14** [comment]
There's another place to improvement
- Weather set broken in small devices
- Result list shouldn't be cut between the same list? I think at the top of each column should start with a title not list item

**Comment by singuerinc** [comment]
@mameaw14 Feel free to open a new Issue or fix them in this PR if you would. Thanks!
